server: 
 port: 9001
 
  
eureka: 
 instance:
  hostname: localhost
 
spring: 
  application: 
   name: api-gateway
  cloud: 
   gateway: 
    routes: 
     - id: Agent-Details
       uri: lb://Agent-Details 
       predicates: 
        - Path=/agentApi/**
     - id: Client-Details
       uri: lb://Client-Details 
       predicates: 
        - Path=/clientApi/**
     - id: Transaction-Details
       uri: lb://Transaction-Details 
       predicates: 
        - Path=/fundtransfer/**